### ISSUE TITLE
Strange EVM logs

### ISSUE THREAD

**Issue by vikiival** [kodadot/click#18]
MY click died because:

```
processor 2022-07-11T09:57:10.832Z INFO ⬤  debug     [[SEND]]: {
processor 2022-07-11T09:57:10.833Z INFO   "from": "0xC0E0e7122c163a8c70c9858E8674C51Fb7117e88",
processor 2022-07-11T09:57:10.833Z INFO   "to": "0x59C481548CE7BA13f3288df9f4FCf44a10A589A0",
processor 2022-07-11T09:57:10.833Z INFO   "tokenId": {
processor 2022-07-11T09:57:10.833Z INFO     "type": "BigNumber",
processor 2022-07-11T09:57:10.833Z INFO     "hex": "0x1f0e"
processor 2022-07-11T09:57:10.833Z INFO   }
processor 2022-07-11T09:57:10.833Z INFO }
processor 2022-07-11T09:57:10.833Z INFO ☐  pending   [SEND]: 2165977
processor 2022-07-11T09:57:10.835Z INFO ⬤  debug     send: {
processor 2022-07-11T09:57:10.835Z INFO   "caller": "0xC0E0e7122c163a8c70c9858E8674C51Fb7117e88",
processor 2022-07-11T09:57:10.835Z INFO   "blockNumber": "2165977",
processor 2022-07-11T09:57:10.835Z INFO   "timestamp": "2022-07-08T18:21:54.461Z",
processor 2022-07-11T09:57:10.835Z INFO   "collectionId": "0xe4edcaaea73684b310fc206405ee80abcec73ee0",
processor 2022-07-11T09:57:10.835Z INFO   "sn": "7950",
processor 2022-07-11T09:57:10.835Z INFO   "to": "0x59C481548CE7BA13f3288df9f4FCf44a10A589A0"
processor 2022-07-11T09:57:10.835Z INFO }
processor 2022-07-11T09:57:10.865Z ERROR ReferenceError: [PROBLEM] Entity  needs to be real
    at needTo (/squid/lib/mappings/utils/consolidator.js:42:15)
    at plsBe (/squid/lib/mappings/utils/consolidator.js:32:12)
    at handleTokenTransfer (/squid/lib/mappings/index.js:132:30)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async technoBunker (/squid/lib/mappings/index.js:198:13)
    at async /squid/node_modules/@subsquid/substrate-processor/lib/processor.js:289:29
    at async /squid/node_modules/@subsquid/substrate-processor/lib/db.js:69:13
```

That means: 
- address [0xC0E0e7122c163a8c70c9858E8674C51Fb7117e88](https://moonriver.moonscan.io/address/0xC0E0e7122c163a8c70c9858E8674C51Fb7117e88)
- was trying to send [PondSama token](https://moonriver.moonscan.io/address/0xe4edcaaea73684b310fc206405ee80abcec73ee0) number 7950

Problem: 
- it died because no such token exists on the database
- according to [moonscan no such operation was done](https://moonriver.moonscan.io/txs?a=0xe4edcaaea73684b310fc206405ee80abcec73ee0&ps=100&p=1)
- Remix shows that the transaction was done to the address [0x59C481548CE7BA13f3288df9f4FCf44a10A589A0](https://moonriver.moonscan.io/address/0x59C481548CE7BA13f3288df9f4FCf44a10A589A0)

<img width="357" alt="Screenshot 2022-07-11 at 12 20 31" src="https://user-images.githubusercontent.com/22471030/178243617-bf367a73-b878-49c4-8400-77720f5d2583.png">

Investigation:
- Looks like [TX has been done](https://moonriver.moonscan.io/tx/0xb54bd3e954bb835e6e1117781a6dadb2856d9c33a253dafa4a449289a8264ac1)
- [Token 7950 was created a minute before transfer](https://moonriver.moonscan.io/token/0xe4edcaaea73684b310fc206405ee80abcec73ee0?a=7950)

**Comment by vikiival** [comment]
Investigation notes:

Somehow the transaction was skipped or so :)

I was able to find the transaction in the subsquid or so

```
⬤  debug     [[MINTNFT]]: [0x0000000000000000000000000000000000000000, 0xC0E0e7122c163a8c70c9858E8674C51Fb7117e88, 7950, 1]
☐  pending   [NFT++]: 2165969
⬤  debug     metadata: ipfs://QmYnbw7YJogZFW9kvxXWYuPdNco2MdTd28SDwzJ7q6kHpB
…  watching  [IPFS] 200 ipfs://QmYnbw7YJogZFW9kvxXWYuPdNco2MdTd28SDwzJ7q6kHpB
✔  success   [MINT] 0xe4edcaaea73684b310fc206405ee80abcec73ee0-7950
⬤  debug     [[SEND]]: [0xC0E0e7122c163a8c70c9858E8674C51Fb7117e88, 0x59C481548CE7BA13f3288df9f4FCf44a10A589A0, 7950, 1]
☐  pending   [SEND]: 2165977
✔  success   [SEND] 0xe4edcaaea73684b310fc206405ee80abcec73ee0-7950 from 0xC0E0e7122c163a8c70c9858E8674C51Fb7117e88 to 0x59C481548CE7BA13f3288df9f4FCf44a10A589A0
Last block: 2166000, mapping: 1 blocks/sec, ingest: 5 blocks/sec, eta: 0s, progress: 100%
```
